### PR TITLE
Add script bin/lnrpc-install

### LINKED ISSUE #10: Replace Release Branches /w Package.json config
Release branches are annoying to maintain instead:
- [ ] Parse root package.json file for any `lnrpc` configuration object containing a `tag` value
- [ ] Remove release branches

### PR DESCRIPTION
**Pull request by OttoAllmendinger**
Add script bin/lnrpc-install

This allows defining the version in the project declaring the `lnrpc`
dependency.

The configuration is read from the `config.lnrpc.version` key of the
parent `package.json`.

Example:
```
{
  "config": {
    "lnrpc": {
      "version": "0.6-beta"
    }
  }
}
```

I chose this format to be consistent with `lnd-binary`:
https://github.com/mrfelton/lnd-binary#configuration

Fixes #10

### CODE REVIEW

**Comment by Matt-Jensen** [comment]
Thanks for whipping up a solution for this, it's been an annoyance for some users.  Did you look into just replacing our Napa implementation with https://github.com/mrfelton/lnd-binary?

**Comment by OttoAllmendinger** [comment]
> Did you look into just replacing our Napa implementation with https://github.com/mrfelton/lnd-binary?

Not an option at the moment, but it should be doable with a some changes. Currently `lnd-binary` only downloads the executables, it would have to be extended to download `lnd-source-v0.6-beta.tar.gz` as well.

I would like to possibly change this PR a little bit since there seems to be a more standard way to access the config in package.json via envvars: https://docs.npmjs.com/misc/config#per-package-config-settings

**Comment by Matt-Jensen** [comment]
Good points.  I agree on leveraging npm's standard of configuration over other options.

Once you have your final changes in, I'll add documentation to this PR in the README.

**Comment by OttoAllmendinger** [comment]
To be honest, I am currently exploring https://github.com/OttoAllmendinger/node-lnd-grpc and it seems to solve the issue of having more control over the protocol version for me. At this point I'm not sure which library I will be going with.

**Comment by Matt-Jensen** [comment]
Aright after reviewing and weighing some pros and cons I think you're approach is generally good, but I'm going to make a few changes.  I've included some of my reasoning as well.

- Call Napa directly.  This PR configures Napa programmatically and I prefer the declarative approach we are currently using, which IMO is easier to understand.  We can accomplish this by installing via [tags and branches](https://github.com/shama/napa#looking-to-just-download-a-tagged-releasea-brancha-specific-commit-on-github-or-just-a-zip-or-targz-url).  I'll re-purpose your script to lookup any custom version or return an empty string, without risking throwing any errors.
- Use your approach of looking up "config" in the root `package.json`, however do not require it to be set.  The current implementation is a breaking change and I want to keep our current happy path of just installing master by default.
- Use current module for looking up root package as the current approach looks risky to me.
- Add logging to inform user of what version of LND they've configured

**Pull request merged**
